name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v2.x

      - name: Run linter
        run: deno lint

      - name: Install dependencies
        run: deno install

      - name: Run build task
        run: deno task build

      - name: Run Deno
        run: deno run --allow-net --allow-read --allow-env main.ts